### ISSUE TITLE
Create ReviewNB integration to allow reviewing jupyter notebooks

### ISSUE THREAD

**Issue by gaursagar21** [PanwarJayant/spot#4]
GitHub doesn't show a visual diff between Jupyter notebooks. We need to integrate a tool like https://www.reviewnb.com/ to make code reviews easier.

**Comment by gaursagar21** [comment]
Assigned to @PanwarJayant because he is the repository owner

**Comment by PanwarJayant** [comment]
Installed the ReviewNB extension into the repository. Please have a look and let me know if it is working accordingly. @gaursagar21

**Comment by PanwarJayant** [comment]
Closing the issue, now that it is resolved.
